### ISSUE TITLE
Allow users to tune out of channels

### ISSUE THREAD

**Issue by patrickklaeren** [patrickklaeren/Accord#10]
Discord allows permissions on a per-channel, per-user basis. Allow users to tune out of channels via a command which adds a permission stipulating that person cannot view that channel.

Three commands:
`channel hide {channel}` - hides channel
`channel show {channel}` - shows channel
`channel hidden` - gets all hidden channels for the user

**Comment by ProIcons** [comment]
Note: If somebody hides a channel they have no way of re-referencing it on `channel show`, unless they remember the channel's id, or 
in `channel show` plain string is used to iterate through the guild's channels and find the channel user wants.
