### ISSUE TITLE
User join/leave logs need to include username in plaintext

### ISSUE THREAD

**Issue by Trinitek** [patrickklaeren/Accord#11]
The current implementation encapsulates the username as a clickable ping, but this will not display the actual username if the Discord client has not cached the name for that ID. This effectively makes join/leave logs unsearchable for a particular name. See image for an example.

![image](https://user-images.githubusercontent.com/6560270/122605069-f1527a80-d044-11eb-916d-0d42872375a8.png)

**Comment by patrickklaeren** [comment]
Fixed with #bc907a9
